apiVersion: v1
kind: PersistentVolume
metadata:
    name: esa-pv
    namespace: default
spec:
    capacity:
        ### This storage capacity value is not enforced at this layer. ###
        storage: 10Gi
    accessModes:
        - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    storageClassName: esa-identity
    csi:
        driver: edgecache.csi.azure.com
        readOnly: false
        volumeHandle: esa-pv
        volumeAttributes:
            protocol: edgecache
            edgecache-storage-auth: ManagedSystemIdentity
            storageAccount: STORAGEACCOUNT
            containerName: STORAGECONTAINER